### ISSUE TITLE
7z still can't open raw_data_ibip19.7z

### ISSUE THREAD

**Issue by iquasere** [GTPB/IBIP19#3]
Greetings

As the [raw_data_ibip19.7z](http://proteomique.ipbs.fr/ibip19/raw_data_ibip19.7z) file still can't be opened with 7z, I wanted to know if the processed files are available at another location, or if using mzdb-specs in the raw data is the only way to go forward on the QC jupyter notebook.

**Comment by david-bouyssie** [comment]
I tried to open the file and there is no issue on my side. The file is bigger than 2GB, which means that some web browser may not be compatible with such a big size. Which web browser are you using?

Alternatively I can split the 7z file in two files if it doesn't work for you.

**Comment by iquasere** [comment]
I ran the wget command, from the windows ubuntu subsystem. Hadn't tried downloading through the web browser yet, and it worked through Chrome! Thank you, David!

**Comment by david-bouyssie** [comment]
Great!
