### ISSUE TITLE
Error on "Estimation of cluster number" in VSCLust

### ISSUE THREAD

**Issue by iquasere** [GTPB/IBIP19#4]
Greetings again! This question goes to Veit!

I want to know what parameters I should set when inputing the "PMC6453966_VSClust_in.csv" file for VSClust. I have set:
* Yes for: "Column names?", "Estimate variance levels from replicated quantifications?" and "Replicates are grouped"
* No for: "Gene/protein identifiers in second column?" and "paired tests"
* Number of replicates: 9
* Number of conditions: 5

With this parameters, when I try to do "Estimation of cluster number", I get
```
Error: non-numeric argument to binary operator
```

**Comment by veitveit** [comment]
I think you have the wrong file. I went through the notebook, created it and loaded it into VSClust without problems
https://drive.google.com/open?id=1VdZSPfT6KSmyBI_svmUP_u2yn4QrJNko
Can you check whether this file works with you?

You might have chosen the wrong columns when creating the file

**Comment by iquasere** [comment]
Of course you were right, I had selected the "PSMs.for.quant" columns. It works perfectly for estimating cluster number. Now I run into the problem of enrichment. I am using the server version of the software, no docker. When I try to "run enrichment", with ID type as "UNIGENE" and Information resource as "GO molecular function" or any other, it fails. "A1BG", the first rowname, is a UniProt gene name, but I also tried setting the ID type for other values and always gives me
```
No result. Wrong ID type?
```
At least the next people will know how to not follow my mistakes xD

**Comment by veitveit** [comment]
Good point. The correct term would be "OFFICIAL_GENE_SYMBOL", but the used R library (RDAVIDWebservice) does not seem capable of using this indentifier. 

You could upload the file that has been prepared for ComplexBrowser as it contains UniProt accession numbers instead. I probably will have to move this conversion to an earlier stage.
