### ISSUE TITLE
Dispersion plot not showing because of colnames

### ISSUE THREAD

**Issue by iquasere** [GTPB/IBIP19#5]
This is a small thing, but still might confuse some people. In the [multivariate analysis notebook](https://github.com/GTPB/IBIP19/blob/master/pages/clustering/Multivariate%20analysis.ipynb), when we make that cool representation of log of protein quantification from one sample against the other:
```
plot(lQuantTable$Set.1.TMT10Tag_126, lQuantTable$Set.1.TMT10Tag_129C, pch=15, col="#33333366")
```
it doesn't work because the colnames of QuantTable have been changed to the cancer types, and lQuantTable inherits the new names.

**Comment by veitveit** [comment]
Thanks, this should have been solved now
